"use client";
import {useEffect,useRef,useState} from "react";
type Props={config?:any;target?:string;onStatus?:(message:string)=>void};
export default function SipSoftphone({config,target,onStatus}:Props){
 const[status,setStatus]=useState("desconectado"),[busy,setBusy]=useState(false),[password,setPassword]=useState("");
 const ua=useRef<any>(null),session=useRef<any>(null),registerer=useRef<any>(null);
 const cfg=config?.regras||{}; const host=String(cfg.sip_host||"").trim(),user=String(cfg.ramal||"").trim(),ws=String(cfg.sip_ws||cfg.websocket||"").trim();
 const set=(v:string)=>{setStatus(v);onStatus?.("Softphone SIP: "+v)};
 const disconnect=async()=>{try{session.current?.bye?.();await registerer.current?.unregister?.();await ua.current?.stop?.()}catch{}session.current=null;registerer.current=null;ua.current=null;setBusy(false);set("desconectado")};
 const connect=async()=>{if(!host||!user||!password){set("configure servidor, ramal e senha SIP");return}try{const {UserAgent,Registerer}=await import("sip.js");const uri=UserAgent.makeURI("sip:"+user+"@"+host);if(!uri)throw new Error("Ramal SIP inválido");const agent=new UserAgent({uri,transportOptions:{server:ws||("wss://"+host)},authorizationUsername:user,authorizationPassword:password});agent.delegate={onInvite:(inv:any)=>{session.current=inv;setBusy(true);set("chamada recebida");void inv.accept?.()}};ua.current=agent;await agent.start();registerer.current=new Registerer(agent);await registerer.current.register();set("conectado")}catch(e:any){set("falha: "+(e?.message||"não foi possível conectar"))}};
 const call=async()=>{if(!ua.current){await connect();return}const clean=String(target||"").replace(/\D/g,"");if(!clean)return;try{const {Inviter,UserAgent}=await import("sip.js");const uri=UserAgent.makeURI("sip:"+clean+"@"+host);if(!uri)throw new Error("Destino inválido");const inv=new Inviter(ua.current,uri);session.current=inv;setBusy(true);set("chamando");await inv.invite()}catch(e:any){set("falha na chamada: "+(e?.message||"erro"));setBusy(false)}};
 useEffect(()=>()=>{void disconnect()},[]);
 return <div className="panel" style={{marginTop:12}}><div className="toolbar"><div><div className="eyebrow">SOFTPHONE SIP / WEBRTC</div><h3>Telefonia incorporada</h3><p>Usa o servidor SIP/WebSocket configurado.</p></div><span className="pill">{status}</span></div><div className="twoFields"><div className="field"><label htmlFor="sip-field-01">Servidor SIP</label><input id="sip-field-01" value={host} readOnly placeholder="sip.exemplo.com.br"/ name="sip-field-01"></div><div className="field"><label htmlFor="sip-field-02">Ramal</label><input id="sip-field-02" value={user} readOnly placeholder="1001"/ name="sip-field-02"></div></div><div className="field"><label htmlFor="sip-field-03">Senha SIP</label><input id="sip-field-03" type="password" value={password} onChange={e= name="sip-field-03">setPassword(e.target.value)} placeholder="Senha do ramal"/></div><div className="actionRow">{!ua.current?<button className="btn primary" onClick={connect}>Conectar SIP</button>:<button className="btn" onClick={disconnect}>Desconectar</button>}<button className="btn" disabled={busy} onClick={call}>☎ Chamar lead atual</button>{busy&&<button className="btn dangerBtn" onClick={()=>{try{session.current?.bye?.()}catch{}setBusy(false);set("desligado")}}>■ Desligar</button>}</div></div>
}
